# Generated by Django 3.1.4 on 2021-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
