# Generated by Django 3.1.4 on 2021-04-29 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermsg_api', '0002_auto_20210429_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermsg',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
