# Generated by Django 3.1.4 on 2021-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_auto_20210426_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
